# Generated by Django 2.0.5 on 2018-05-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=191)),
                ('slug', models.CharField(max_length=191, unique=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
            ],
            options={
                'verbose_name': 'athlete',
                'verbose_name_plural': 'athletes',
            },
        ),
        migrations.CreateModel(
            name='AthleteEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Athlete')),
            ],
            options={
                'verbose_name': 'athlete event',
                'verbose_name_plural': 'athlete events',
            },
        ),
        migrations.CreateModel(
            name='AthleteTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Athlete')),
            ],
            options={
                'verbose_name': 'athlete team',
                'verbose_name_plural': 'athlete teams',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_id', models.PositiveIntegerField()),
                ('amount', models.IntegerField()),
                ('won', models.BooleanField(choices=[(True, 'Won'), (False, 'Lost')], default=False)),
            ],
            options={
                'verbose_name': 'bet',
                'verbose_name_plural': 'bets',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=191, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='starts at')),
                ('banner', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='banner')),
                ('thumb', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='', verbose_name='thumbnail')),
                ('winner_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Winner ID')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
            },
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event')),
            ],
            options={
                'verbose_name': 'event teams',
                'verbose_name_plural': 'event teams',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=191, verbose_name='name')),
                ('slug', models.CharField(max_length=191, unique=True, verbose_name='slug')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('banner', models.CharField(blank=True, max_length=191, null=True, verbose_name='banner')),
                ('thumb', models.CharField(blank=True, max_length=191, null=True, verbose_name='thumb')),
                ('icon', models.CharField(blank=True, max_length=191, null=True, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'game',
                'verbose_name_plural': 'games',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('details', models.TextField(blank=True, null=True, verbose_name='details')),
                ('image', models.CharField(blank=True, max_length=191, null=True)),
                ('athletes', models.ManyToManyField(related_name='teams', to='core.Athlete', verbose_name='athletes')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Game', verbose_name='game')),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_type', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('details', models.TextField(blank=True, null=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Bet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.AddField(
            model_name='eventteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.EventCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Game', verbose_name='game'),
        ),
        migrations.AddField(
            model_name='bet',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Event'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='athleteteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='athleteevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Event'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Game'),
        ),
    ]
