# Generated by Django 2.0.5 on 2018-05-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180521_0924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='na',
            new_name='name',
        ),
    ]
