# Generated by Django 2.0.5 on 2018-05-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180521_0925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_category',
            new_name='category',
        ),
    ]
