# Generated by Django 2.0.5 on 2018-05-21 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180521_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ('name',), 'verbose_name': 'event category', 'verbose_name_plural': 'event categories'},
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bet',
            name='won',
            field=models.NullBooleanField(choices=[(None, 'Wait'), (True, 'Won'), (False, 'Lost')], default=None),
        ),
    ]
