# Generated by Django 2.0.5 on 2018-05-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180521_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='won',
        ),
        migrations.AddField(
            model_name='bet',
            name='status',
            field=models.NullBooleanField(choices=[(None, 'Wait'), (True, 'Won'), (False, 'Lost')], default=None, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='bet',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
