# Generated by Django 2.0.5 on 2018-05-22 13:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20180521_1229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bet',
            unique_together={('user', 'event')},
        ),
    ]
