# Generated by Django 2.0.5 on 2018-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180522_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.FileField(blank=True, default='', upload_to='', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='logo url'),
        ),
    ]
