# Generated by Django 2.0.5 on 2018-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180524_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='bet percent')),
            ],
            options={
                'verbose_name': 'site config',
                'verbose_name_plural': 'site config',
            },
        ),
    ]
