# Generated by Django 2.0.5 on 2018-05-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='system_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
