# Generated by Django 2.0.5 on 2018-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180531_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bet',
            name='system_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20),
        ),
    ]
