# Generated by Django 2.0.5 on 2018-05-23 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(default='', max_length=512, verbose_name='Stripe id')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAIL', 'Fail')], default='CREATED', max_length=8, verbose_name='Status')),
                ('error', models.TextField(blank=True, default='', verbose_name='error')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment record',
                'verbose_name_plural': 'payment records',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.CharField(max_length=256, verbose_name='stripe customer id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stripe customer',
                'verbose_name_plural': 'Stripe customers',
            },
        ),
    ]
