# Generated by Django 2.0.5 on 2018-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='deposit'),
            preserve_default=False,
        ),
    ]
