# Generated by Django 2.0.5 on 2018-05-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15, verbose_name='deposit'),
        ),
    ]
